# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 10x-dux-app 

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up pipenv and Install dependencies
      uses: dschep/install-pipenv-action@c90124a0ca1de8a0cc0d7763b4a92a96b56b6377
      with:
        version: 2020.6.2
      run: |
        pipenv install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to cloud.gov (DEV)
        if: github.ref == 'refs/heads/develop'
        uses: cloud-gov/cg-cli-tools@faa8ea4e4c784e50ddddc6859b382efaad9774b9
        with: 
          cf_api: ${{ secrets.CG_ENDPOINT }}
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_org: ${{ secrets.CG_ORG }}
          cf_space: ${{ secrets.CG_SPACE }}
          cf_command: push -f manifest.yml 10x-dux-app-dev1 --var vuls_http_server=${{ secrets.VULS_HTTP_SERVER }}
      - name: Deploy to cloud.gov (UAT)
        if: github.ref == 'refs/heads/master'
        uses: cloud-gov/cg-cli-tools@faa8ea4e4c784e50ddddc6859b382efaad9774b9
        with: 
          cf_api: ${{ secrets.CG_ENDPOINT }}
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_org: ${{ secrets.CG_ORG }}
          cf_space: ${{ secrets.CG_SPACE }}
          cf_command: push -f manifest.yml 10x-dux-app-uat1 --var vuls_http_server=${{ secrets.VULS_HTTP_SERVER }}
