# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate SBOM Report

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up pipenv
      uses: dschep/install-pipenv-action@aaac0310d5f4a052d150e5f490b44354e08fbb8c
      with:
        version: 2020.6.2
    - name: Install dependencies and generate in place requirements.txt file
      run: |
        pipenv install --dev
        pipenv lock --requirements > requirements.txt

