# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate SBOM Report

on:
  pull_request:
    branches:
      - develop

jobs:
  analyze-sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up pipenv
      uses: dschep/install-pipenv-action@aaac0310d5f4a052d150e5f490b44354e08fbb8c
      with:
        version: 2020.6.2
    - name: Install dependencies and generate in place requirements.txt file
      run: |
        pipenv install --dev
        pipenv lock --requirements > requirements.txt
    - name: Generate CycloneDX SBOM report
      uses: CycloneDX/gh-python-generate-sbom@9847fabb5866e97354c28fe5f1d6fa8b71e3b38d # current v1 tag
    - name: Upload CycloneDX report to project artifacts
      uses: actions/upload-artifact@27bce4eee761b5bc643f46a8dfb41b430c8d05f6 # current v2 tag
      with:
        name: sbom-cyclonedx
        path: ./bom.xml
        if-no-files-found: error